# ===== Floating =====
windowrulev2 = float, class:^(blueman-manager)$
windowrulev2 = float, class:^(nm-connection-editor)$
windowrulev2 = float, class:^(pavucontrol)$
windowrulev2 = float, class:^(rofi)$
windowrulev2 = center, class:^(rofi)$

# ===== Firefox Picture-in-Picture =====
windowrulev2 = float, title:^(Picture-in-Picture)$
windowrulev2 = pin,   title:^(Picture-in-Picture)$

# ===== Dialogs =====
windowrulev2 = float, class:^(xdg-desktop-portal-gtk)$
windowrulev2 = center, class:^(xdg-desktop-portal-gtk)$
